name: iptv_player
description: Lecteur IPTV multiplateforme (Android, Android TV, Windows).
publish_to: 'none'
version: 6.2.0+10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  xml: ^6.5.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  file_picker: ^12.0.0
  wakelock_plus: ^1.2.8
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/banner.png

flutter_launcher_icons:
  android: true
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true
